spring:
  application:
    name: gateway
  
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token
#            authorization-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth
#            userinfo-uri: http://localhost:8080/realms/master/protocol/openid-connect/userinfo
            #jwk-set-uri:  http://localhost:8080/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        #resourceserver:
          #jwt:
            #jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

        registration:
          keycloak-with-developer-scope:
            provider: keycloak
            client-id: user1
            client-secret: gYQ6gqYKNzzl8socR9uvQfz9B4vc4SV7
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: dev
          keycloak-with-tester-scope:
            provider: keycloak
            client-id: user2
            client-secret: CzgM2aQD6wH8su1N2nSPNxMDCM3x9Tiv
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: tester
  securitySchemes:
    my_oAuth_security_schema:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/oauth2/authorize
          scopes:
            read_access: read data
            write_access: modify data

server.port: 7060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE